version: "3"

services:
  postgres:
    image: "postgres:alpine"
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    networks:
      - keycloak
  keycloakx:
    # image: quay.io/keycloak/keycloak-x:latest
    build: # "context" and "dockerfile" fields have to be under "build"
      context: dev
      dockerfile: .Dockerfile
      # image: keycloaxdev:v0.1
      # network: host
      # image: quay.io/keycloak/keycloak-x:latest
      # cache_from:
      #   - quay.io/keycloak/keycloak-x:latest
    container_name: keycloakx
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: 127.0.0.1:8080
      KC_HTTP_ENABLED: "true"
      # PROXY_ADDRESS_FORWARDING: "true"
    #command: start-dev --db=postgres -Dkc.db.url.host=postgres --db-username=keycloak --db-password=password
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - keycloak
networks:
  keycloak:
    driver: bridge