version: "3"

services:
  postgres:
    image: "postgres:alpine"
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    networks:
      - keycloak
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: "rabbitmq"
    environment:
      RABBITMQ_VHOST: "/"
      RABBITMQ_USERNAME: keycloak
      RABBITMQ_PASSWORD: keycloak77
      RABBITMQ_PLUGINS: rabbitmq_management
      RABBITMQ_MANAGEMENT_PORT_NUMBER: 15672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/bitnami
    networks:
      - keycloak
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    networks:
      - keycloak
    ports:
      - 8025:8025
  keycloak-gosns:
    image: keycloak-gosns:latest
    container_name: keycloak-gosns
    restart: "always"
    secrets:
        - source: awssns_env
          target: /dist/.env
    networks:
      - keycloak
    depends_on:
      - rabbitmq
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    volumes:
      # Script to deploy module
      #- ./scripts/deploy-module.cli:/opt/jboss/startup-scripts/00-deploy-module.cli
      # Script to disable theme caching
      - ./scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/01-disable-theme-cache.cli      
      # Script to add SPI properties to the keycloak standalone.xml file; the properties are used in the SPI extension for configuration
      - ./keycloak-spi-amqp-mfa-events/scripts/add-config.cli:/opt/jboss/startup-scripts/add-config.cli
      # Keycloak SPI extensions
      - ./keycloak-spi-amqp-mfa-events/target/com.mbecker-keycloak-spi-amqp-mfa-events-0.1-SNAPSHOT.jar:/opt/jboss/keycloak/standalone/deployments/com.mbecker-keycloak-spi-amqp-mfa-events-0.1-SNAPSHOT.jar
      # Keycloak original Themes for development
      - ./themes/:/opt/jboss/keycloak/themes
    environment:
      AMQPMFAEVENTS_CONFIG_IS_SIMULATION: "false"
      AMQPMFAEVENTS_CONFIG_NOTIFICATION_SHOULD_SEND_ON_STARTUP: "false" # TODO: Add to cli script
      AMQPMFAEVENTS_CONFIG_NOTIFICATION_CHANNELS: AMQP,EMAIL # TODO: Add to cli script
      AMQPMFAEVENTS_CONFIG_AMQP_HOST: rabbitmq
      AMQPMFAEVENTS_CONFIG_AMQP_QUEUE: notification
      AMQPMFAEVENTS_CONFIG_AMQP_USERNAME: keycloak
      AMQPMFAEVENTS_CONFIG_AMQP_PASSWORD: keycloak77
      AMQPMFAEVENTS_CONFIG_SHOULD_SKIP: "true"
      AMQPMFAEVENTS_CONFIG_AMQP_QUEUE_EVENTS: events
      AMQPMFAEVENTS_CONFIG_AMQP_QUEUE_EVENTS_ADMIN: eventsadmin
      KEYCLOAK_LOGLEVEL: INFO
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: sack77
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
      - mailhog
    networks:
      - keycloak
networks:
  keycloak:
    driver: bridge
secrets:
   awssns_env:
     file: keycloak-gomfasnsevents/dockercompose.env
   
